# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/mnt/data" =
    { device = "/dev/mapper/data";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."data" = {
    device = "/dev/disk/by-uuid/b3144f8b-87c9-4685-95bb-85510d4b5582";
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1db2329d-d8c4-4c26-8304-0571b1fe7206";
      fsType = "ext4";
    };

    fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4AD1-E6D0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/var/lib/vms" =
    { device = "/dev/disk/by-uuid/d77aadc0-7fbb-4eb5-a274-d337461116cf";
      fsType = "ext4";
    };

    swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
