local pack_add = Config.pack_add

pack_add({
	"nvim-mini/mini.nvim",
	"supermaven-inc/supermaven-nvim",
	-- "zbirenbaum/copilot.lua",
	-- "fang2hou/blink-copilot",
	"MeanderingProgrammer/render-markdown.nvim",
	"neovim/nvim-lspconfig",
	"mfussenegger/nvim-lint",
	"luukvbaal/statuscol.nvim",
	"lewis6991/gitsigns.nvim",
	"AlexvZyl/nordic.nvim",
	"iamcco/markdown-preview.nvim",
	"dmtrKovalenko/fff.nvim",
	"stevearc/conform.nvim",
	"stevearc/oil.nvim",
	"stevearc/dressing.nvim",
	{ src = "nvim-treesitter/nvim-treesitter", version = "main" },
	-- { src = "nvim-treesitter/nvim-treesitter-textobjects", version = "main" },
	-- "arborist-ts/arborist.nvim",
	"windwp/nvim-ts-autotag",
	"nvim-treesitter/nvim-treesitter-context",
	"JoosepAlviste/nvim-ts-context-commentstring",
	"pmizio/typescript-tools.nvim",
	"nvim-lua/plenary.nvim",
	"mrcjkb/rustaceanvim",
	"j-hui/fidget.nvim",
	{ src = "saghen/blink.pairs", version = "v0.5.0" },
	{ src = "saghen/blink.cmp", version = "v1.10.2" },
	"saghen/blink.download",
	"saghen/blink.chartoggle",
	"folke/lazydev.nvim",
	"saghen/blink.indent",
	"bydlw98/blink-cmp-env",
	"moyiz/blink-emoji.nvim",
	"MahanRahmati/blink-nerdfont.nvim",
	"xzbdmw/colorful-menu.nvim",
	"folke/snacks.nvim",
	"Kaiser-Yang/blink-cmp-dictionary",
	"L3MON4D3/LuaSnip",
	"disrupted/blink-cmp-conventional-commits",
	"mason-org/mason.nvim",
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	"refractalize/oil-git-status.nvim",
	"JezerM/oil-lsp-diagnostics.nvim",
	"lewis6991/gitsigns.nvim",
	"kawre/leetcode.nvim",
	"MunifTanjim/nui.nvim",
	"nvim-flutter/flutter-tools.nvim",
	"seblyng/roslyn.nvim",
	"esmuellert/codediff.nvim",
	-- "NeogitOrg/neogit",
	"epwalsh/obsidian.nvim",
	"L3MON4D3/LuaSnip",
	"rafamadriz/friendly-snippets",
})
